# Generated by Django 4.2.15 on 2025-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, null=True)),
                ('number', models.CharField(max_length=9, null=True)),
                ('color', models.CharField(max_length=20, null=True)),
                ('release_year', models.CharField(max_length=4, null=True)),
                ('brand', models.CharField(max_length=20, null=True)),
                ('current_mileage', models.IntegerField(null=True)),
                ('last_inspection_mileage', models.IntegerField(null=True)),
                ('daily_mileage', models.IntegerField(null=True)),
                ('usage_conditions', models.CharField(choices=[('city', 'Город'), ('highway', 'Шоссе'), ('off-road', 'Бездорожье'), ('mixed', 'Смешанный')], max_length=10, null=True)),
                ('driving_style', models.CharField(choices=[('calm', 'Спокойный'), ('universal', 'Универсальный'), ('agressive', 'Агрессивный')], max_length=13, null=True)),
                ('usage_type', models.CharField(choices=[('personal', 'Личный'), ('taxi', 'Такси'), ('rental', 'Прокат'), ('delivery', 'Доставка')], max_length=8, null=True)),
                ('oil', models.IntegerField(null=True)),
                ('oil_filter', models.IntegerField(null=True)),
                ('belt', models.IntegerField(null=True)),
                ('transmission', models.IntegerField(null=True)),
                ('air_filter', models.IntegerField(null=True)),
                ('cabin_filter', models.IntegerField(null=True)),
                ('fuel_filter', models.IntegerField(null=True)),
                ('coolant', models.IntegerField(null=True)),
                ('spark_plugs', models.IntegerField(null=True)),
                ('brake_fluid', models.IntegerField(null=True)),
                ('brakes', models.IntegerField(null=True)),
                ('shocks', models.IntegerField(null=True)),
                ('steering', models.IntegerField(null=True)),
                ('battery', models.IntegerField(null=True)),
                ('tires', models.IntegerField(null=True)),
                ('quiz_date', models.DateTimeField(null=True)),
                ('last_inspection_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
